#!/bin/bash

#openmpi

export GCCVER=8.3.1
module --force purge
module load lrun/2020.03.05 gcc/8.3.1
spack compiler find
spack load --first gcc@${GCCVER}
spack env activate -d ./spack-environments/openmpi-lassen || exit 1
spack concretize -f || exit 1
spack install -j 8 || exit 1
spack load cmake cuda hdf5 mpi || exit 1
export OMPI_MCA_fs_ufs_lock_algorithm=1
export OMPI_MCA_btl_openib_allow_ib=1

